server:
  port: 82

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DanQingDB?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    content-type: text/html

mybatis:
  type-aliases-package: com.boot.danqing.entity
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com:
      boot:
        danqing:
          Dao: debug

